hardly_check = true
per_gov_check = false
tcp_bbr3_check = false
cachy_config_check = true
nconfig_check = false
xconfig_check = false
localmodcfg_check = false
use_current_check = false
builtin_zfs_check = false
builtin_nvidia_open_check = false
build_debug_check = false
hz_ticks_combo = "1000"
tickrate_combo = "full"
preempt_combo = "full"
hugepage_combo = "always"
lto_combo = "thin"
cpu_opt_combo = "native"
custom_name_edit = "$pkgbase-x0rzavi"
